spring:
  # Load database configuration from system environment variables
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/backendsim?useSSL=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

# Production Log configuration
logging:
  level:
    root: WARN
    com.backendsim.platform: INFO
    org.springframework: WARN
    org.hibernate: WARN
